# Generated by Django 4.0.6 on 2022-07-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Question_description',
            field=models.CharField(default='Basic Description', max_length=255),
        ),
    ]
